#pragma once
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/ShapeInferenceInterface.h"
#include "mlir/IR/PatternMatch.h"
#define GET_OP_CLASSES
#include "mlir/VoilaOps.h.inc"